steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --pull
      - --file=apps/mobile_staging_broker/Dockerfile
      - --tag=${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
