steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/management-system-docker-repo/${_SERVICE_NAME}-image:tag1',
      '.'
    ]
    automapSubstitutions: true

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/management-system-docker-repo/${_SERVICE_NAME}-image:tag1'
    ]
    automapSubstitutions: true
    
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud run deploy ${_SERVICE_NAME} \
        --image ${_REGION}-docker.pkg.dev/$PROJECT_ID/management-system-docker-repo/${_SERVICE_NAME}-image:tag1 \
        --update-secrets=DSN_PASSWORD=supabase-database-password:latest \
        --region ${_REGION} \
        --platform managed \
        --no-allow-unauthenticated \
        --env-vars-file .env.yaml
    env:
    - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'

options:
  substitutionOption: 'ALLOW_LOOSE'