-- GENERATED FILE: do not edit by hand.
-- Source: Alembic 0003_legacy_bigint_activity_game -> 0004_phase_c_identity_lifecycle.
-- LOCAL REHEARSAL/REVIEW ONLY. PRODUCTION EXECUTION REQUIRES SEPARATE OWNER APPROVAL.

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

-- Running upgrade 0003_legacy_bigint_activity_game -> 0004_phase_c_identity_lifecycle

ALTER TABLE ntubtob.people ADD COLUMN formal_name varchar(120) NULL;
        ALTER TABLE ntubtob.people ADD COLUMN admin_note varchar(1000) NULL;
        ALTER TABLE ntubtob.people ADD CONSTRAINT ck_people_formal_name
          CHECK (formal_name IS NULL OR length(btrim(formal_name)) BETWEEN 1 AND 120);
        ALTER TABLE ntubtob.people ADD CONSTRAINT ck_people_admin_note
          CHECK (admin_note IS NULL OR length(btrim(admin_note)) BETWEEN 1 AND 1000);

        ALTER TABLE ntubtob.access_audit DROP CONSTRAINT ck_access_audit_action;
        ALTER TABLE ntubtob.access_audit ADD CONSTRAINT ck_access_audit_action
          CHECK (action IN ('identity_pending', 'identity_linked', 'identity_ignored', 'identity_unignored', 'identity_unlinked', 'identity_remapped', 'identity_disabled', 'identity_enabled', 'identity_rejected', 'identity_unblocked', 'identity_blocked', 'person_approved', 'person_profile_updated', 'access_changed', 'status_changed', 'qualification_granted', 'qualification_revoked', 'qualification_restored', 'review_message_sent', 'review_closed', 'review_redacted', 'member_backfilled'));

        CREATE TABLE ntubtob.identity_review_threads (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          auth_identity_id bigint NOT NULL REFERENCES ntubtob.auth_identities(id) ON DELETE RESTRICT,
          status varchar(20) NOT NULL DEFAULT 'open',
          last_applicant_message_at timestamptz NULL,
          last_activity_at timestamptz NOT NULL,
          closed_at timestamptz NULL,
          redacted_at timestamptz NULL,
          created_at timestamptz NOT NULL,
          updated_at timestamptz NOT NULL,
          CONSTRAINT uq_identity_review_thread UNIQUE (auth_identity_id),
          CONSTRAINT ck_identity_review_thread_status CHECK (status IN ('open', 'closed')),
          CONSTRAINT ck_identity_review_thread_closed CHECK
            ((status = 'open' AND closed_at IS NULL) OR (status = 'closed' AND closed_at IS NOT NULL))
        );
        CREATE TABLE ntubtob.identity_review_messages (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          thread_id bigint NOT NULL REFERENCES ntubtob.identity_review_threads(id) ON DELETE RESTRICT,
          sender_role varchar(20) NOT NULL,
          sender_person_id bigint NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          body text NULL,
          body_redacted boolean NOT NULL DEFAULT false,
          created_at timestamptz NOT NULL,
          CONSTRAINT ck_identity_review_sender CHECK
            ((sender_role = 'applicant' AND sender_person_id IS NULL) OR
             (sender_role = 'admin' AND sender_person_id IS NOT NULL)),
          CONSTRAINT ck_identity_review_body CHECK
            ((body_redacted IS FALSE AND length(body) BETWEEN 1 AND 1000) OR
             (body_redacted IS TRUE AND body IS NULL))
        );
        CREATE INDEX ix_identity_review_threads_status_activity
          ON ntubtob.identity_review_threads(status, last_activity_at);
        CREATE INDEX ix_identity_review_messages_thread_created
          ON ntubtob.identity_review_messages(thread_id, created_at, id);
        ALTER TABLE ntubtob.identity_review_threads ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.identity_review_messages ENABLE ROW LEVEL SECURITY;

        ALTER TABLE ntubtob.person_qualifications ADD CONSTRAINT ck_guest_player_bounded
          CHECK (qualification <> 'guest_player' OR
            (valid_from IS NOT NULL AND valid_until IS NOT NULL AND
             valid_until > valid_from AND valid_until <= valid_from + interval '5 years'));

        ALTER TABLE ntubtob.game_attendance_replies ADD COLUMN person_id bigint NULL;
        DO $phase_c_member$
        DECLARE
          legacy_member record;
          new_person_id bigint;
        BEGIN
          FOR legacy_member IN
            SELECT DISTINCT m.id, m.name
            FROM ntubtob.game_attendance_replies r
            JOIN ntubtob.members m ON m.id = r.member_id
            WHERE m.person_id IS NULL
            ORDER BY m.id
          LOOP
            INSERT INTO ntubtob.people
              (display_name, formal_name, portal_access_level, portal_status,
               version, created_at, updated_at)
            VALUES
              (legacy_member.name, legacy_member.name, 'basic', 'inactive',
               1, now(), now())
            RETURNING id INTO new_person_id;
            UPDATE ntubtob.members SET person_id = new_person_id
              WHERE id = legacy_member.id AND person_id IS NULL;
            INSERT INTO ntubtob.person_qualifications
              (person_id, qualification, status, valid_from, valid_until,
               granted_by_person_id, reason, created_at, updated_at)
            VALUES
              (new_person_id, 'team_player', 'active', NULL, NULL, NULL,
               'Phase C attendance compatibility backfill', now(), now());
            INSERT INTO ntubtob.access_audit
              (action, actor_person_id, target_person_id, auth_identity_id,
               before_state, after_state, reason, request_id, created_at)
            VALUES
              ('member_backfilled', NULL, new_person_id, NULL,
               json_build_object('member_id', legacy_member.id, 'person_id', NULL),
               json_build_object('member_id', legacy_member.id, 'person_id', new_person_id),
               'Phase C attendance compatibility backfill',
               'phase-c-attendance-member-' || legacy_member.id, now());
          END LOOP;
        END
        $phase_c_member$;
        UPDATE ntubtob.game_attendance_replies r SET person_id=m.person_id
          FROM ntubtob.members m WHERE m.id=r.member_id AND r.person_id IS NULL;
        DO $phase_c$
        BEGIN
          IF EXISTS (SELECT 1 FROM ntubtob.game_attendance_replies WHERE person_id IS NULL) THEN
            RAISE EXCEPTION 'Phase C attendance backfill has unresolved Person rows';
          END IF;
        END
        $phase_c$;
        ALTER TABLE ntubtob.game_attendance_replies ADD CONSTRAINT fk_game_attendance_person
          FOREIGN KEY (person_id) REFERENCES ntubtob.people(id) ON DELETE RESTRICT;
        CREATE INDEX ix_game_attendance_person_game_updated
          ON ntubtob.game_attendance_replies(person_id, game_id, updated_at DESC, id DESC);;

UPDATE ntubtob.alembic_version SET version_num='0004_phase_c_identity_lifecycle' WHERE ntubtob.alembic_version.version_num = '0003_legacy_bigint_activity_game';

COMMIT;
