"""Add the local Person, access, qualification, and Event foundation.

Revision ID: 0002_portal_data_foundation
Revises: 0001_legacy_baseline
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0002_portal_data_foundation"
down_revision: Union[str, None] = "0001_legacy_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE ntubtob.people (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          display_name varchar(120) NOT NULL,
          portal_access_level varchar(20) NOT NULL,
          portal_status varchar(20) NOT NULL,
          version integer NOT NULL DEFAULT 1,
          created_at timestamptz NOT NULL,
          updated_at timestamptz NOT NULL,
          CONSTRAINT ck_people_access_level CHECK
            (portal_access_level IN ('basic', 'officer', 'admin')),
          CONSTRAINT ck_people_status CHECK
            (portal_status IN ('pending', 'active', 'disabled', 'inactive', 'blocked'))
        );

        ALTER TABLE ntubtob.members ADD COLUMN person_id bigint NULL;
        ALTER TABLE ntubtob.members ADD CONSTRAINT uq_members_person_id UNIQUE (person_id);
        ALTER TABLE ntubtob.members ADD CONSTRAINT fk_members_person
          FOREIGN KEY (person_id) REFERENCES ntubtob.people(id) ON DELETE RESTRICT;

        CREATE TABLE ntubtob.auth_identities (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          provider varchar(20) NOT NULL,
          provider_subject varchar(255) NOT NULL,
          person_id bigint NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          status varchar(20) NOT NULL,
          created_at timestamptz NOT NULL,
          updated_at timestamptz NOT NULL,
          CONSTRAINT uq_auth_provider_subject UNIQUE (provider, provider_subject),
          CONSTRAINT ck_auth_provider CHECK (provider IN ('line', 'google', 'apple')),
          CONSTRAINT ck_auth_status CHECK (status IN ('pending', 'linked', 'disabled', 'blocked')),
          CONSTRAINT ck_auth_link_state CHECK (
            (status = 'pending' AND person_id IS NULL) OR
            (status = 'linked' AND person_id IS NOT NULL) OR
            status IN ('disabled', 'blocked')
          )
        );

        CREATE TABLE ntubtob.person_qualifications (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          person_id bigint NOT NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          qualification varchar(30) NOT NULL,
          status varchar(20) NOT NULL,
          valid_from timestamptz NULL,
          valid_until timestamptz NULL,
          granted_by_person_id bigint NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          reason varchar(300) NULL,
          created_at timestamptz NOT NULL,
          updated_at timestamptz NOT NULL,
          CONSTRAINT uq_person_qualification UNIQUE (person_id, qualification),
          CONSTRAINT ck_qualification_value CHECK
            (qualification IN ('team_player', 'guest_player', 'affiliate', 'staff')),
          CONSTRAINT ck_qualification_status CHECK (status IN ('active', 'revoked')),
          CONSTRAINT ck_qualification_dates CHECK
            (valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from)
        );

        CREATE TABLE ntubtob.access_audit (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          action varchar(40) NOT NULL,
          actor_person_id bigint NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          target_person_id bigint NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          auth_identity_id bigint NULL REFERENCES ntubtob.auth_identities(id) ON DELETE RESTRICT,
          before_state json NULL,
          after_state json NULL,
          reason varchar(300) NOT NULL,
          request_id varchar(100) NOT NULL,
          created_at timestamptz NOT NULL,
          CONSTRAINT uq_access_audit_request UNIQUE (request_id),
          CONSTRAINT ck_access_audit_reason CHECK (length(reason) BETWEEN 3 AND 300),
          CONSTRAINT ck_access_audit_action CHECK (action IN (
            'identity_linked', 'identity_blocked', 'access_changed', 'status_changed',
            'qualification_granted', 'qualification_revoked', 'member_backfilled'
          ))
        );

        CREATE TABLE ntubtob.events (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title varchar(200) NOT NULL,
          event_type varchar(30) NOT NULL,
          status varchar(20) NOT NULL,
          start_at timestamptz NOT NULL,
          end_at timestamptz NULL,
          created_by_person_id bigint NOT NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          published_at timestamptz NULL,
          version integer NOT NULL DEFAULT 1,
          created_at timestamptz NOT NULL,
          updated_at timestamptz NOT NULL,
          CONSTRAINT ck_event_type CHECK
            (event_type IN ('game', 'meal', 'trip', 'practice', 'social', 'other')),
          CONSTRAINT ck_event_status CHECK (status IN ('draft', 'published', 'cancelled')),
          CONSTRAINT ck_event_dates CHECK (end_at IS NULL OR end_at > start_at)
        );

        CREATE TABLE ntubtob.activities (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id bigint NOT NULL REFERENCES ntubtob.events(id) ON DELETE CASCADE,
          title varchar(200) NOT NULL,
          activity_type varchar(30) NOT NULL,
          position integer NOT NULL,
          start_at timestamptz NOT NULL,
          end_at timestamptz NULL,
          game_id integer NULL REFERENCES ntubtob.games(id) ON DELETE RESTRICT,
          CONSTRAINT uq_activity_position UNIQUE (event_id, position),
          CONSTRAINT ck_activity_type CHECK
            (activity_type IN ('game', 'meal', 'transport', 'lodging', 'gathering', 'other')),
          CONSTRAINT ck_activity_dates CHECK (end_at IS NULL OR end_at > start_at)
        );

        CREATE TABLE ntubtob.event_eligibility_rules (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id bigint NOT NULL REFERENCES ntubtob.events(id) ON DELETE CASCADE,
          qualification varchar(30) NOT NULL,
          CONSTRAINT uq_event_eligibility UNIQUE (event_id, qualification),
          CONSTRAINT ck_event_eligibility_value CHECK
            (qualification IN ('team_player', 'guest_player', 'affiliate', 'staff'))
        );

        CREATE TABLE ntubtob.event_invitee_overrides (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id bigint NOT NULL REFERENCES ntubtob.events(id) ON DELETE CASCADE,
          person_id bigint NOT NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          action varchar(20) NOT NULL,
          participation_category varchar(30) NOT NULL,
          actor_person_id bigint NOT NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          reason varchar(300) NOT NULL,
          created_at timestamptz NOT NULL,
          CONSTRAINT uq_event_invitee_override UNIQUE (event_id, person_id),
          CONSTRAINT ck_invitee_override_action CHECK (action IN ('include', 'exclude')),
          CONSTRAINT ck_invitee_override_category CHECK
            (participation_category IN ('team_player', 'guest_player', 'affiliate', 'staff', 'other')),
          CONSTRAINT ck_invitee_override_reason CHECK (length(reason) BETWEEN 3 AND 300)
        );

        CREATE TABLE ntubtob.event_invitees (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id bigint NOT NULL REFERENCES ntubtob.events(id) ON DELETE CASCADE,
          person_id bigint NOT NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          included boolean NOT NULL,
          source varchar(30) NOT NULL,
          source_qualification varchar(30) NULL,
          participation_category varchar(30) NOT NULL,
          actor_person_id bigint NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          reason varchar(300) NULL,
          snapshotted_at timestamptz NOT NULL,
          CONSTRAINT uq_event_invitee UNIQUE (event_id, person_id),
          CONSTRAINT ck_event_invitee_source CHECK
            (source IN ('qualification', 'manual_include', 'manual_exclude')),
          CONSTRAINT ck_event_participation_category CHECK
            (participation_category IN ('team_player', 'guest_player', 'affiliate', 'staff', 'other')),
          CONSTRAINT ck_event_invitee_source_fields CHECK (
            (source = 'qualification' AND source_qualification IS NOT NULL AND actor_person_id IS NULL) OR
            (source IN ('manual_include', 'manual_exclude') AND actor_person_id IS NOT NULL
             AND length(reason) BETWEEN 3 AND 300)
          )
        );

        CREATE TABLE ntubtob.event_attendance_replies (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id bigint NOT NULL REFERENCES ntubtob.events(id) ON DELETE CASCADE,
          person_id bigint NOT NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          reply varchar(20) NOT NULL,
          updated_at timestamptz NOT NULL,
          CONSTRAINT uq_event_attendance_reply UNIQUE (event_id, person_id),
          CONSTRAINT ck_event_attendance_reply CHECK
            (reply IN ('attending', 'not_attending', 'maybe'))
        );

        CREATE TABLE ntubtob.activity_attendance_replies (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          activity_id bigint NOT NULL REFERENCES ntubtob.activities(id) ON DELETE CASCADE,
          person_id bigint NOT NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          reply varchar(20) NOT NULL,
          updated_at timestamptz NOT NULL,
          CONSTRAINT uq_activity_attendance_reply UNIQUE (activity_id, person_id),
          CONSTRAINT ck_activity_attendance_reply CHECK
            (reply IN ('attending', 'not_attending', 'maybe'))
        );

        CREATE TABLE ntubtob.event_managers (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id bigint NOT NULL REFERENCES ntubtob.events(id) ON DELETE CASCADE,
          person_id bigint NOT NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          assigned_by_person_id bigint NOT NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          created_at timestamptz NOT NULL,
          CONSTRAINT uq_event_manager UNIQUE (event_id, person_id)
        );

        CREATE TABLE ntubtob.event_audit (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_id bigint NOT NULL REFERENCES ntubtob.events(id) ON DELETE CASCADE,
          actor_person_id bigint NOT NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          action varchar(30) NOT NULL,
          reason varchar(300) NOT NULL,
          request_id varchar(100) NOT NULL,
          details json NULL,
          created_at timestamptz NOT NULL,
          CONSTRAINT uq_event_audit_request UNIQUE (request_id),
          CONSTRAINT ck_event_audit_reason CHECK (length(reason) BETWEEN 3 AND 300),
          CONSTRAINT ck_event_audit_action CHECK
            (action IN ('published', 'invitee_included', 'invitee_excluded'))
        );

        CREATE INDEX ix_auth_identities_person ON ntubtob.auth_identities(person_id);
        CREATE INDEX ix_person_qualifications_active
          ON ntubtob.person_qualifications(qualification, person_id) WHERE status = 'active';
        CREATE INDEX ix_event_invitees_event_included
          ON ntubtob.event_invitees(event_id, included, participation_category);

        CREATE FUNCTION ntubtob.reject_audit_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'audit rows are append-only';
        END;
        $$;
        CREATE TRIGGER access_audit_append_only
          BEFORE UPDATE OR DELETE ON ntubtob.access_audit
          FOR EACH ROW EXECUTE FUNCTION ntubtob.reject_audit_mutation();
        CREATE TRIGGER event_audit_append_only
          BEFORE UPDATE OR DELETE ON ntubtob.event_audit
          FOR EACH ROW EXECUTE FUNCTION ntubtob.reject_audit_mutation();

        ALTER TABLE ntubtob.people ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.auth_identities ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.person_qualifications ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.access_audit ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.events ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.activities ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.event_eligibility_rules ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.event_invitee_overrides ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.event_invitees ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.event_attendance_replies ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.activity_attendance_replies ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.event_managers ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.event_audit ENABLE ROW LEVEL SECURITY
        """
    )


def downgrade() -> None:
    # Local rehearsal only. Production rollback retains expand schema.
    op.execute(
        """
        DROP TABLE ntubtob.event_audit;
        DROP TABLE ntubtob.event_managers;
        DROP TABLE ntubtob.activity_attendance_replies;
        DROP TABLE ntubtob.event_attendance_replies;
        DROP TABLE ntubtob.event_invitees;
        DROP TABLE ntubtob.event_invitee_overrides;
        DROP TABLE ntubtob.event_eligibility_rules;
        DROP TABLE ntubtob.activities;
        DROP TABLE ntubtob.events;
        DROP TABLE ntubtob.access_audit;
        DROP TABLE ntubtob.person_qualifications;
        DROP TABLE ntubtob.auth_identities;
        ALTER TABLE ntubtob.members DROP CONSTRAINT fk_members_person;
        ALTER TABLE ntubtob.members DROP CONSTRAINT uq_members_person_id;
        ALTER TABLE ntubtob.members DROP COLUMN person_id;
        DROP TABLE ntubtob.people;
        DROP FUNCTION IF EXISTS ntubtob.reject_audit_mutation();
        """
    )
