"""Add durable mobile auth and idempotency state.

Revision ID: 0005_mobile_auth_api_foundation
Revises: 0004_phase_c_identity_lifecycle
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0005_mobile_auth_api_foundation"
down_revision: Union[str, None] = "0004_phase_c_identity_lifecycle"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
    CREATE TABLE ntubtob.mobile_sessions (
      id varchar(64) PRIMARY KEY,
      auth_identity_id bigint NOT NULL REFERENCES ntubtob.auth_identities(id) ON DELETE RESTRICT,
      person_id bigint NOT NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
      installation_id_hash varchar(64) NOT NULL,
      platform varchar(20) NOT NULL,
      status varchar(20) NOT NULL,
      access_epoch integer NOT NULL,
      refresh_family_expires_at timestamptz NOT NULL,
      revoked_at timestamptz NULL,
      created_at timestamptz NOT NULL,
      updated_at timestamptz NOT NULL,
      CONSTRAINT ck_mobile_sessions_status CHECK (status IN ('active', 'revoked')),
      CONSTRAINT ck_mobile_sessions_platform CHECK (platform IN ('ios', 'android')),
      CONSTRAINT ck_mobile_sessions_access_epoch CHECK (access_epoch >= 1),
      CONSTRAINT ck_mobile_sessions_expiry CHECK (refresh_family_expires_at > created_at)
    );
    CREATE INDEX ix_mobile_sessions_person_status ON ntubtob.mobile_sessions(person_id, status);
    CREATE TABLE ntubtob.mobile_refresh_tokens (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      session_id varchar(64) NOT NULL REFERENCES ntubtob.mobile_sessions(id) ON DELETE CASCADE,
      token_hash varchar(64) NOT NULL,
      generation integer NOT NULL,
      status varchar(20) NOT NULL,
      successor_token_id bigint NULL REFERENCES ntubtob.mobile_refresh_tokens(id) ON DELETE RESTRICT,
      issued_at timestamptz NOT NULL, expires_at timestamptz NOT NULL,
      rotated_at timestamptz NULL, revoked_at timestamptz NULL,
      CONSTRAINT uq_mobile_refresh_token_hash UNIQUE (token_hash),
      CONSTRAINT uq_mobile_refresh_generation UNIQUE (session_id, generation),
      CONSTRAINT ck_mobile_refresh_status CHECK (status IN ('current', 'rotated', 'revoked')),
      CONSTRAINT ck_mobile_refresh_generation CHECK (generation >= 1)
    );
    CREATE INDEX ix_mobile_refresh_session_status ON ntubtob.mobile_refresh_tokens(session_id, status);
    CREATE TABLE ntubtob.mobile_refresh_attempts (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      session_id varchar(64) NOT NULL REFERENCES ntubtob.mobile_sessions(id) ON DELETE CASCADE,
      attempt_id_hash varchar(64) NOT NULL, request_hash varchar(64) NOT NULL,
      encrypted_successor bytea NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL,
      CONSTRAINT uq_mobile_refresh_attempt UNIQUE (session_id, attempt_id_hash)
    );
    CREATE INDEX ix_mobile_refresh_attempts_expiry ON ntubtob.mobile_refresh_attempts(expires_at);
    CREATE TABLE ntubtob.mobile_idempotency_records (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      session_id varchar(64) NOT NULL REFERENCES ntubtob.mobile_sessions(id) ON DELETE CASCADE,
      person_id bigint NOT NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
      method varchar(10) NOT NULL, route varchar(160) NOT NULL,
      key_hash varchar(64) NOT NULL, request_hash varchar(64) NOT NULL,
      state varchar(20) NOT NULL, response_status integer NULL, response_body json NULL,
      expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL,
      CONSTRAINT uq_mobile_idempotency_scope UNIQUE (session_id, method, route, key_hash),
      CONSTRAINT ck_mobile_idempotency_state CHECK (state IN ('pending', 'completed'))
    );
    CREATE INDEX ix_mobile_idempotency_expiry ON ntubtob.mobile_idempotency_records(expires_at);
    CREATE TABLE ntubtob.mobile_auth_exchanges (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      provider varchar(20) NOT NULL, assertion_hash varchar(64) NOT NULL,
      login_attempt_hash varchar(64) NOT NULL,
      session_id varchar(64) NOT NULL REFERENCES ntubtob.mobile_sessions(id) ON DELETE RESTRICT,
      expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL,
      CONSTRAINT uq_mobile_auth_assertion UNIQUE (provider, assertion_hash),
      CONSTRAINT uq_mobile_auth_attempt UNIQUE (provider, login_attempt_hash),
      CONSTRAINT ck_mobile_auth_provider CHECK (provider IN ('line', 'google', 'apple'))
    );
    CREATE INDEX ix_mobile_auth_exchanges_expiry ON ntubtob.mobile_auth_exchanges(expires_at);
    ALTER TABLE ntubtob.mobile_sessions ENABLE ROW LEVEL SECURITY;
    ALTER TABLE ntubtob.mobile_refresh_tokens ENABLE ROW LEVEL SECURITY;
    ALTER TABLE ntubtob.mobile_refresh_attempts ENABLE ROW LEVEL SECURITY;
    ALTER TABLE ntubtob.mobile_idempotency_records ENABLE ROW LEVEL SECURITY;
    ALTER TABLE ntubtob.mobile_auth_exchanges ENABLE ROW LEVEL SECURITY;
    """
    )


def downgrade() -> None:
    op.execute(
        """
    DROP TABLE ntubtob.mobile_auth_exchanges;
    DROP TABLE ntubtob.mobile_idempotency_records;
    DROP TABLE ntubtob.mobile_refresh_attempts;
    DROP TABLE ntubtob.mobile_refresh_tokens;
    DROP TABLE ntubtob.mobile_sessions;
    """
    )
