"""Add durable member-visible mobile notifications.

Revision ID: 0007_mobile_notifications
Revises: 0006_staging_broker_operation_journal
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0007_mobile_notifications"
down_revision: Union[str, None] = "0006_staging_broker_operation_journal"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
    CREATE TABLE ntubtob.mobile_notifications (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      notification_type varchar(40) NOT NULL,
      title varchar(120) NOT NULL,
      body varchar(500) NOT NULL,
      created_at timestamptz NOT NULL,
      visible_until timestamptz NOT NULL,
      CONSTRAINT ck_mobile_notification_type CHECK (
        notification_type IN (
          'game_reminder', 'attendance_reminder', 'game_change',
          'officer_personal', 'officer_game_broadcast',
          'officer_team_broadcast', 'admin_system_announcement'
        )
      ),
      CONSTRAINT ck_mobile_notification_title CHECK (
        length(btrim(title)) BETWEEN 1 AND 120
      ),
      CONSTRAINT ck_mobile_notification_body CHECK (
        length(btrim(body)) BETWEEN 1 AND 500
      ),
      CONSTRAINT ck_mobile_notification_visibility CHECK (
        visible_until > created_at
        AND visible_until <= created_at + interval '90 days'
      )
    );
    CREATE INDEX ix_mobile_notifications_created
      ON ntubtob.mobile_notifications(created_at DESC, id DESC);

    CREATE TABLE ntubtob.mobile_notification_recipients (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      notification_id bigint NOT NULL
        REFERENCES ntubtob.mobile_notifications(id) ON DELETE RESTRICT,
      person_id bigint NOT NULL
        REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
      created_at timestamptz NOT NULL,
      read_at timestamptz NULL,
      CONSTRAINT uq_mobile_notification_recipient
        UNIQUE (notification_id, person_id),
      CONSTRAINT ck_mobile_notification_read_time CHECK (
        read_at IS NULL OR read_at >= created_at
      )
    );
    CREATE INDEX ix_mobile_notification_recipient_page
      ON ntubtob.mobile_notification_recipients(
        person_id, notification_id DESC
      );
    CREATE INDEX ix_mobile_notification_recipient_unread
      ON ntubtob.mobile_notification_recipients(person_id, notification_id)
      WHERE read_at IS NULL;

    CREATE FUNCTION ntubtob.reject_mobile_notification_mutation()
    RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION 'mobile notification content is immutable';
    END;
    $$;
    CREATE TRIGGER mobile_notification_content_immutable
      BEFORE UPDATE OR DELETE ON ntubtob.mobile_notifications
      FOR EACH ROW EXECUTE FUNCTION ntubtob.reject_mobile_notification_mutation();

    ALTER TABLE ntubtob.mobile_notifications ENABLE ROW LEVEL SECURITY;
    ALTER TABLE ntubtob.mobile_notification_recipients ENABLE ROW LEVEL SECURITY;
    """
    )


def downgrade() -> None:
    op.execute(
        """
    DROP TABLE ntubtob.mobile_notification_recipients;
    DROP TABLE ntubtob.mobile_notifications;
    DROP FUNCTION ntubtob.reject_mobile_notification_mutation();
    """
    )
