"""Add Officer publishing audit, delivery outbox, devices and typed destinations.

Revision ID: 0008_mobile_notification_delivery
Revises: 0007_mobile_notifications
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0008_mobile_notification_delivery"
down_revision: Union[str, None] = "0007_mobile_notifications"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
    ALTER TABLE ntubtob.mobile_notifications
      ADD COLUMN destination_type varchar(20) NOT NULL DEFAULT 'notification',
      ADD COLUMN destination_game_id bigint NULL
        REFERENCES ntubtob.games(id) ON DELETE RESTRICT,
      ADD CONSTRAINT ck_mobile_notification_destination CHECK (
        (destination_type = 'notification' AND destination_game_id IS NULL) OR
        (destination_type = 'game' AND destination_game_id IS NOT NULL)
      );
    ALTER TABLE ntubtob.mobile_notifications
      ALTER COLUMN destination_type DROP DEFAULT;

    CREATE TABLE ntubtob.mobile_notification_publish_audits (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      notification_id bigint NOT NULL
        REFERENCES ntubtob.mobile_notifications(id) ON DELETE RESTRICT,
      actor_person_id bigint NOT NULL
        REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
      audience_type varchar(20) NOT NULL,
      audience_reference_id bigint NULL,
      preview_revision char(64) NOT NULL,
      recipient_count integer NOT NULL,
      request_hash char(64) NOT NULL,
      created_at timestamptz NOT NULL,
      CONSTRAINT uq_mobile_notification_publish_audit UNIQUE (notification_id),
      CONSTRAINT ck_mobile_notification_audit_audience CHECK (
        audience_type IN ('individual', 'game', 'team')
      ),
      CONSTRAINT ck_mobile_notification_audit_recipient_count CHECK (
        recipient_count BETWEEN 1 AND 500
      )
    );

    CREATE TABLE ntubtob.mobile_notification_deliveries (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      notification_id bigint NOT NULL
        REFERENCES ntubtob.mobile_notifications(id) ON DELETE RESTRICT,
      channel varchar(20) NOT NULL,
      status varchar(20) NOT NULL,
      attempt_count integer NOT NULL,
      error_code varchar(80) NULL,
      retryable boolean NOT NULL,
      created_at timestamptz NOT NULL,
      updated_at timestamptz NOT NULL,
      CONSTRAINT uq_mobile_notification_delivery UNIQUE (notification_id, channel),
      CONSTRAINT ck_mobile_notification_delivery_channel CHECK (
        channel IN ('in_app', 'push')
      ),
      CONSTRAINT ck_mobile_notification_delivery_status CHECK (
        status IN ('pending', 'succeeded', 'failed')
      ),
      CONSTRAINT ck_mobile_notification_attempt_count CHECK (attempt_count >= 0)
    );
    CREATE INDEX ix_mobile_notification_delivery_outbox
      ON ntubtob.mobile_notification_deliveries(status, channel, id)
      WHERE status IN ('pending', 'failed') AND retryable IS TRUE;

    CREATE TABLE ntubtob.mobile_device_registrations (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      person_id bigint NOT NULL REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
      session_id varchar(64) NOT NULL
        REFERENCES ntubtob.mobile_sessions(id) ON DELETE RESTRICT,
      installation_id_hash char(64) NOT NULL,
      platform varchar(20) NOT NULL,
      provider varchar(20) NOT NULL,
      token_hash char(64) NOT NULL,
      status varchar(20) NOT NULL,
      created_at timestamptz NOT NULL,
      updated_at timestamptz NOT NULL,
      revoked_at timestamptz NULL,
      CONSTRAINT uq_mobile_device_installation UNIQUE (person_id, installation_id_hash),
      CONSTRAINT ck_mobile_device_platform CHECK (platform IN ('ios', 'android')),
      CONSTRAINT ck_mobile_device_provider CHECK (provider = 'fake'),
      CONSTRAINT ck_mobile_device_status CHECK (status IN ('active', 'revoked'))
    );
    CREATE UNIQUE INDEX uq_mobile_device_active_provider_token
      ON ntubtob.mobile_device_registrations(provider, token_hash)
      WHERE status = 'active';

    CREATE FUNCTION ntubtob.reject_mobile_notification_audit_mutation()
    RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      RAISE EXCEPTION 'mobile notification audit is append-only';
    END;
    $$;
    CREATE TRIGGER mobile_notification_audit_immutable
      BEFORE UPDATE OR DELETE ON ntubtob.mobile_notification_publish_audits
      FOR EACH ROW EXECUTE FUNCTION ntubtob.reject_mobile_notification_audit_mutation();

    ALTER TABLE ntubtob.mobile_notification_publish_audits ENABLE ROW LEVEL SECURITY;
    ALTER TABLE ntubtob.mobile_notification_deliveries ENABLE ROW LEVEL SECURITY;
    ALTER TABLE ntubtob.mobile_device_registrations ENABLE ROW LEVEL SECURITY;
    """
    )


def downgrade() -> None:
    op.execute(
        """
    DROP TABLE ntubtob.mobile_device_registrations;
    DROP TABLE ntubtob.mobile_notification_deliveries;
    DROP TABLE ntubtob.mobile_notification_publish_audits;
    DROP FUNCTION ntubtob.reject_mobile_notification_audit_mutation();
    ALTER TABLE ntubtob.mobile_notifications
      DROP CONSTRAINT ck_mobile_notification_destination,
      DROP COLUMN destination_game_id,
      DROP COLUMN destination_type;
    """
    )
