"""Add encrypted Apple provider lifecycle and notification receipts.

Revision ID: 0010_apple_provider_lifecycle
Revises: 0009_event_management_writes
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0010_apple_provider_lifecycle"
down_revision: Union[str, None] = "0009_event_management_writes"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE ntubtob.apple_provider_code_exchanges (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          code_hash char(64) NOT NULL,
          login_attempt_hash char(64) NOT NULL,
          state varchar(20) NOT NULL,
          auth_identity_id bigint NULL REFERENCES ntubtob.auth_identities(id) ON DELETE RESTRICT,
          created_at timestamptz NOT NULL,
          updated_at timestamptz NOT NULL,
          CONSTRAINT uq_apple_provider_code_hash UNIQUE (code_hash),
          CONSTRAINT uq_apple_provider_login_attempt_hash UNIQUE (login_attempt_hash),
          CONSTRAINT ck_apple_provider_code_state CHECK (
            state IN ('pending', 'completed', 'rejected', 'unknown')
          )
        );

        CREATE TABLE ntubtob.apple_provider_credentials (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          auth_identity_id bigint NOT NULL REFERENCES ntubtob.auth_identities(id) ON DELETE RESTRICT,
          encrypted_refresh_token bytea NOT NULL,
          refresh_token_hash char(64) NOT NULL,
          status varchar(20) NOT NULL,
          created_at timestamptz NOT NULL,
          updated_at timestamptz NOT NULL,
          revoked_at timestamptz NULL,
          CONSTRAINT uq_apple_provider_credential_identity UNIQUE (auth_identity_id),
          CONSTRAINT ck_apple_provider_credential_status CHECK (
            status IN ('active', 'revoked')
          )
        );

        CREATE TABLE ntubtob.apple_provider_notifications (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          jti_hash char(64) NOT NULL,
          event_type varchar(40) NOT NULL,
          disposition varchar(20) NOT NULL,
          auth_identity_id bigint NULL REFERENCES ntubtob.auth_identities(id) ON DELETE RESTRICT,
          event_at timestamptz NOT NULL,
          created_at timestamptz NOT NULL,
          CONSTRAINT uq_apple_provider_notification_jti UNIQUE (jti_hash),
          CONSTRAINT ck_apple_provider_notification_type CHECK (
            event_type IN (
              'consent-revoked', 'account-deleted',
              'email-disabled', 'email-enabled'
            )
          ),
          CONSTRAINT ck_apple_provider_notification_disposition CHECK (
            disposition IN ('revoked', 'receipt_only')
          )
        );

        ALTER TABLE ntubtob.apple_provider_code_exchanges ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.apple_provider_credentials ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.apple_provider_notifications ENABLE ROW LEVEL SECURITY;
        """
    )


def downgrade() -> None:
    # Provider credentials and revocation receipts are security evidence. An
    # automatic downgrade must never restore a revoked identity or delete them.
    pass
