"""Add Event notification and guest-player lifecycle evidence.

Revision ID: 0011_event_notification_guest_lifecycle
Revises: 0010_apple_provider_lifecycle
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0011_event_notification_guest_lifecycle"
down_revision: Union[str, None] = "0010_apple_provider_lifecycle"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE ntubtob.person_qualifications
          ADD COLUMN version integer NOT NULL DEFAULT 1,
          ADD CONSTRAINT ck_person_qualification_version CHECK (version > 0);

        ALTER TABLE ntubtob.mobile_notifications
          ADD COLUMN destination_event_id bigint NULL
            REFERENCES ntubtob.events(id) ON DELETE RESTRICT,
          DROP CONSTRAINT ck_mobile_notification_type,
          ADD CONSTRAINT ck_mobile_notification_type CHECK (
            notification_type IN (
              'game_reminder', 'attendance_reminder', 'game_change',
              'officer_personal', 'officer_game_broadcast',
              'officer_team_broadcast', 'admin_system_announcement',
              'event_published', 'event_updated', 'event_cancelled'
            )
          ),
          DROP CONSTRAINT ck_mobile_notification_destination,
          ADD CONSTRAINT ck_mobile_notification_destination CHECK (
            (destination_type = 'notification' AND
              destination_game_id IS NULL AND destination_event_id IS NULL) OR
            (destination_type = 'game' AND
              destination_game_id IS NOT NULL AND destination_event_id IS NULL) OR
            (destination_type = 'event' AND
              destination_game_id IS NULL AND destination_event_id IS NOT NULL)
          );

        ALTER TABLE ntubtob.mobile_notification_recipients
          ADD COLUMN participation_category varchar(30) NULL,
          ADD CONSTRAINT ck_mobile_notification_recipient_category CHECK (
            participation_category IS NULL OR participation_category IN (
              'team_player', 'guest_player', 'affiliate', 'staff', 'other'
            )
          );

        CREATE TABLE ntubtob.event_notification_publish_audits (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          notification_id bigint NOT NULL
            REFERENCES ntubtob.mobile_notifications(id) ON DELETE RESTRICT,
          event_id bigint NOT NULL REFERENCES ntubtob.events(id) ON DELETE RESTRICT,
          event_audit_id bigint NOT NULL
            REFERENCES ntubtob.event_audit(id) ON DELETE RESTRICT,
          actor_person_id bigint NOT NULL
            REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          notification_type varchar(30) NOT NULL,
          event_version integer NOT NULL,
          preview_revision char(64) NOT NULL,
          recipient_count integer NOT NULL,
          request_id varchar(100) NOT NULL,
          request_hash char(64) NOT NULL,
          created_at timestamptz NOT NULL,
          CONSTRAINT uq_event_notification_audit_notification UNIQUE (notification_id),
          CONSTRAINT uq_event_notification_audit_request UNIQUE (request_id),
          CONSTRAINT ck_event_notification_audit_type CHECK (
            notification_type IN ('event_published', 'event_updated', 'event_cancelled')
          ),
          CONSTRAINT ck_event_notification_audit_version CHECK (event_version > 0),
          CONSTRAINT ck_event_notification_audit_recipients CHECK (
            recipient_count BETWEEN 1 AND 500
          )
        );

        CREATE TABLE ntubtob.guest_qualification_audits (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          qualification_id bigint NOT NULL
            REFERENCES ntubtob.person_qualifications(id) ON DELETE RESTRICT,
          target_person_id bigint NOT NULL
            REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          actor_person_id bigint NOT NULL
            REFERENCES ntubtob.people(id) ON DELETE RESTRICT,
          action varchar(20) NOT NULL,
          expected_version integer NOT NULL,
          resulting_version integer NOT NULL,
          reason varchar(300) NOT NULL,
          request_id varchar(100) NOT NULL,
          request_hash char(64) NOT NULL,
          before_state jsonb NULL,
          after_state jsonb NOT NULL,
          created_at timestamptz NOT NULL,
          CONSTRAINT uq_guest_qualification_audit_request UNIQUE (request_id),
          CONSTRAINT ck_guest_qualification_audit_action CHECK (
            action IN ('granted', 'extended', 'revoked')
          ),
          CONSTRAINT ck_guest_qualification_audit_versions CHECK (
            expected_version >= 0 AND resulting_version > 0
          ),
          CONSTRAINT ck_guest_qualification_audit_reason CHECK (
            length(reason) BETWEEN 3 AND 300
          )
        );

        CREATE INDEX ix_event_notification_audits_event
          ON ntubtob.event_notification_publish_audits(event_id, id);
        CREATE INDEX ix_guest_qualification_audits_target
          ON ntubtob.guest_qualification_audits(target_person_id, id);

        CREATE TRIGGER event_notification_publish_audits_append_only
          BEFORE UPDATE OR DELETE ON ntubtob.event_notification_publish_audits
          FOR EACH ROW EXECUTE FUNCTION ntubtob.reject_audit_mutation();
        CREATE TRIGGER guest_qualification_audits_append_only
          BEFORE UPDATE OR DELETE ON ntubtob.guest_qualification_audits
          FOR EACH ROW EXECUTE FUNCTION ntubtob.reject_audit_mutation();

        ALTER TABLE ntubtob.event_notification_publish_audits ENABLE ROW LEVEL SECURITY;
        ALTER TABLE ntubtob.guest_qualification_audits ENABLE ROW LEVEL SECURITY;
        """
    )


def downgrade() -> None:
    # Notification recipient snapshots and qualification audit history are
    # durable security evidence. Automatic downgrade must not delete them or
    # weaken their constraints.
    pass
