import os
from flask import Flask, abort, jsonify
from time import sleep
from datetime import datetime, timedelta, time
import uuid

from linebot.v3.messaging.models.message import Message
from linebot.v3.messaging import (
    Configuration,
    ApiClient,
    MessagingApi,
    BroadcastRequest,
    PushMessageRequest,
    ReplyMessageRequest,
    ApiException
)
from shared_module.notify.discord_notify import DiscordNotifyHelper

discord_notify_helper = DiscordNotifyHelper()

configuration = Configuration(access_token=os.environ.get("CHANNEL_ACCESS_TOKEN"))

def notify_successful_log(message: str):
    discord_notify_helper.notify_successful_log(message)
def notify_alarm_log(message: str):
    discord_notify_helper.notify_alarm_log(message)
def notify_management_message(message: str):
    discord_notify_helper.notify_management_message(message)

def broadcast(messages: list[Message]) -> bool:
    with ApiClient(configuration) as api_client:
        # Create an instance of the API class
        api_instance = MessagingApi(api_client)
        broadcast_request = BroadcastRequest(messages=messages) # BroadcastRequest | 
        x_line_retry_key = str(uuid.uuid4()) # str | Retry key. Specifies the UUID in hexadecimal format (e.g., `123e4567-e89b-12d3-a456-426614174000`) generated by any method. The retry key isn't generated by LINE. Each developer must generate their own retry key.  (optional)
        reason = ''
        for _ in range(3):
            try:
                api_response = api_instance.broadcast_with_http_info(broadcast_request, x_line_retry_key=x_line_retry_key)
                status_code = api_response.status_code
                if status_code == 500:
                    notify_alarm_log(f"LINE broadcast failed - status_code={status_code}, reason=\n{api_response.raw_data}")
                else:
                    return True
            except Exception as e:
                reason = "Exception when calling LINE Messaging API -> broadcast: %s\n" % e
            sleep(5)
        
        notify_alarm_log(f"LINE broadcast failed - reason=\n{reason}")
        return False
    
def push(id: str, messages: list[Message]) -> bool:
    with ApiClient(configuration) as api_client:
        # Create an instance of the API class
        api_instance = MessagingApi(api_client)
        reply_request = PushMessageRequest(to=id, messages=messages)
        x_line_retry_key = str(uuid.uuid4()) # str | Retry key. Specifies the UUID in hexadecimal format (e.g., `123e4567-e89b-12d3-a456-426614174000`) generated by any method. The retry key isn't generated by LINE. Each developer must generate their own retry key.  (optional)
        
        try:
            api_instance.push_message_with_http_info(reply_request, x_line_retry_key)
        except ApiException as e:
            notify_alarm_log(f"Exception when calling LINE Messaging API -> reply_message: {e}\n")
    
def reply(reply_token: str, messages: list[Message]) -> bool:
    with ApiClient(configuration) as api_client:
        # Create an instance of the API class
        api_instance = MessagingApi(api_client)
        try:
            api_instance.reply_message_with_http_info(
                ReplyMessageRequest(
                    reply_token=reply_token,
                    messages=messages
                )
            )
        except ApiException as e:
            notify_alarm_log(f"Exception when calling LINE Messaging API -> reply_message: {e}\n")