from __future__ import annotations

import os

from sqlalchemy import create_engine, text

from shared_lib.shared_module.portal_data.local_database import (
    require_local_database_url,
)

LEGACY_FIXTURE_SQL = """
CREATE SCHEMA IF NOT EXISTS ntubtob;
CREATE TABLE IF NOT EXISTS ntubtob.members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  enroll_year smallint NULL,
  major varchar NULL,
  number smallint NULL,
  positions varchar NULL
);
CREATE TABLE IF NOT EXISTS ntubtob.attendance_reply_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description varchar NOT NULL
);
CREATE TABLE IF NOT EXISTS ntubtob.ballparks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  city_name varchar NULL,
  city_weather_code varchar NULL,
  district_name varchar NULL
);
CREATE TABLE IF NOT EXISTS ntubtob.games (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year smallint NULL,
  season smallint NULL,
  start_datetime timestamptz NULL,
  duration smallint NULL,
  location varchar NULL,
  home_team varchar NULL,
  away_team varchar NULL,
  invitation_time timestamptz NULL,
  cancellation_time timestamptz NULL,
  cancellation_announcement_time timestamptz NULL
);
CREATE TABLE IF NOT EXISTS ntubtob.cancellations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id bigint NOT NULL REFERENCES ntubtob.games(id),
  cancellation_time timestamptz NOT NULL,
  announced boolean NULL
);
CREATE TABLE IF NOT EXISTS ntubtob.discord_webhooks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  webhook_identifier varchar NOT NULL,
  description varchar NULL,
  created_at timestamptz NULL
);
CREATE TABLE IF NOT EXISTS ntubtob.line_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line_group_id varchar NULL,
  description varchar NULL,
  is_broadcast_enabled boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ntubtob.line_notify_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token varchar NOT NULL,
  description varchar NULL
);
CREATE TABLE IF NOT EXISTS ntubtob.line_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nickname varchar NOT NULL,
  line_user_id varchar NOT NULL,
  member_id bigint NULL REFERENCES ntubtob.members(id),
  submit_time timestamptz NULL DEFAULT (now() AT TIME ZONE 'CCT'::text),
  has_replied boolean NOT NULL DEFAULT false,
  ignored boolean NOT NULL DEFAULT false
);
CREATE TABLE IF NOT EXISTS ntubtob.game_attendance_replies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id bigint NOT NULL REFERENCES ntubtob.games(id),
  user_id bigint NULL REFERENCES ntubtob.line_users(id),
  member_id bigint NULL REFERENCES ntubtob.members(id),
  reply smallint NOT NULL REFERENCES ntubtob.attendance_reply_types(id),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE ntubtob.attendance_reply_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE ntubtob.ballparks ENABLE ROW LEVEL SECURITY;
ALTER TABLE ntubtob.cancellations ENABLE ROW LEVEL SECURITY;
ALTER TABLE ntubtob.discord_webhooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE ntubtob.game_attendance_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE ntubtob.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE ntubtob.line_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE ntubtob.line_notify_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE ntubtob.line_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE ntubtob.members ENABLE ROW LEVEL SECURITY;
INSERT INTO ntubtob.attendance_reply_types (id, description) VALUES
  (9101, 'fictional attending'),
  (9102, 'fictional not attending'),
  (9103, 'fictional maybe')
ON CONFLICT (id) DO NOTHING;
INSERT INTO ntubtob.members (id, name, enroll_year, major, number, positions) VALUES
  (9201, '虛構校友甲', 100, '虛構系所', 1, '虛構守位'),
  (9202, '虛構校友乙', 101, '虛構系所', 2, '虛構守位')
ON CONFLICT (id) DO NOTHING;
INSERT INTO ntubtob.ballparks
  (id, name, city_name, city_weather_code, district_name) VALUES
  (9301, '虛構球場', '虛構城市', 'fictional-code', '虛構行政區')
ON CONFLICT (id) DO NOTHING;
INSERT INTO ntubtob.games
  (id, year, season, start_datetime, duration, location, home_team, away_team,
   invitation_time, cancellation_time, cancellation_announcement_time) VALUES
  (9401, 126, 1, '2037-01-01 01:00:00+00', 180, '虛構球場', '虛構主隊', '虛構客隊',
   NULL, NULL, NULL),
  (9402, 126, 1, '2037-01-08 01:00:00+00', 180, '虛構球場', '虛構主隊', '虛構客隊',
   '2037-01-01 01:00:00+00', '2037-01-02 01:00:00+00', NULL)
ON CONFLICT (id) DO NOTHING;
INSERT INTO ntubtob.line_users
  (id, nickname, line_user_id, member_id, has_replied, ignored) VALUES
  (9501, '虛構已連結', 'fake-line-linked', 9201, true, false),
  (9502, '虛構待配對', 'fake-line-pending', NULL, false, false),
  (9503, '虛構已忽略', 'fake-line-ignored', NULL, false, true)
ON CONFLICT (id) DO NOTHING;
INSERT INTO ntubtob.game_attendance_replies
  (id, game_id, user_id, member_id, reply, updated_at) VALUES
  (9601, 9401, 9501, 9201, 9103, '2037-01-01 00:00:00+00'),
  (9602, 9401, 9501, 9201, 9101, '2037-01-01 00:01:00+00'),
  (9603, 9402, 9501, 9201, 9102, '2037-01-02 00:00:00+00'),
  (9604, 9402, 9501, 9201, 9102, '2037-01-02 00:01:00+00')
ON CONFLICT (id) DO NOTHING;
"""


def main() -> None:
    database_url = require_local_database_url(
        os.environ.get("PORTAL_DATA_DATABASE_URL")
    )
    engine = create_engine(database_url)
    with engine.begin() as connection:
        connection.execute(text(LEGACY_FIXTURE_SQL))
    engine.dispose()
    print("local legacy fixture ready")


if __name__ == "__main__":
    main()
